# Generated by Django 3.2 on 2023-02-28 19:25

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewuser',
            name='username',
            field=models.CharField(help_text='Как к Вам обращаться?', max_length=150, unique=True, validators=[users.validators.validate_username_not_me], verbose_name='Имя пользователя'),
        ),
    ]
