# Generated by Django 3.2 on 2023-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_reviewuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Введите имя пользователя', max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='reviewuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Введите Вашу фамилию', max_length=150, verbose_name='Фамилия пользователя'),
        ),
    ]
