# Generated by Django 3.2 on 2023-03-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_reviewuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewuser',
            name='email',
            field=models.EmailField(help_text='Введите адрес электронной почты', max_length=254, unique=True, verbose_name='адрес электронной почты'),
        ),
    ]
