# Generated by Django 3.2 on 2023-03-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_reviewuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewuser',
            options={'ordering': ('username',)},
        ),
    ]
